CREATE TABLE Categories (
	Id SERIAL NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE ToDoItems (
	Id SERIAL NOT NULL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	DueDate TIMESTAMP NOT NULL,
	Completed BOOL NOT NULL,
	CategoryId INT NOT NULL
);

ALTER TABLE TodoItems ADD CONSTRAINT fkCategoryId FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE;
ALTER TABLE Categories ADD CONSTRAINT ukCategoryName UNIQUE (Name);
